# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week5 Assessment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week5 Assessment
  pod ‘SwiftyJSON’, ‘3.0.0’
  pod 'Alamofire', '~> 4.0'

end
